(() => {
  const customsHeading = document.querySelector('#customs-regulation-title');
  const customsSection = customsHeading?.closest('.source-section');
  if (!customsSection || document.querySelector('#workshop-logistics-docs-title')) return;

  const section = document.createElement('section');
  section.className = 'source-section';
  section.setAttribute('aria-labelledby', 'workshop-logistics-docs-title');
  section.innerHTML = `
    <p class="source-kicker">Workshop documentary genres</p>
    <h2 id="workshop-logistics-docs-title">Waybills, customs receipts, crate sketches and shipment lists</h2>
    <p class="source-note">The Rakow finding aid itself contains a compact logistics dossier inside Series 04, Business Files. These titles are now indexed as retrieval targets rather than left under a generic archive citation. Container numbers are withheld where the PDF text extraction does not securely align them to individual titles. Machine-readable register: <a href="workshop-logistics-document-register.json" target="_blank" rel="noopener">workshop-logistics-document-register.json ↗</a>.</p>
    <div class="source-list"></div>
  `;

  const list = section.querySelector('.source-list');
  const rakowLink = '<a href="https://info.cmog.org/library" target="_blank" rel="noopener">Rakow archival collections / finding aids ↗</a>';
  const records = [
    {
      type: '1907–1911 · rail and customs documentation',
      title: 'International Rail Transport Waybill (1907) and Customs Receipts (1907–1911).',
      meta: 'Two unusually concrete documentary genres survive in the workshop Business Files. The waybill can expose consignor, consignee, route, case marks, weight, freight class and charges; the customs receipts can supply port, broker, date, payment and administrative classification. They are high-priority companions to the 1906–1911 Harvard correspondence.',
      links: rakowLink
    },
    {
      type: '1929 · case architecture and contents',
      title: '“List of Specimens Sent” (1929) and Sketches of Packed Crates (1929, 1932).',
      meta: 'These sources allow the packing chain to be reconstructed at object and container level: which subjects travelled, how inner units related to outer cases, and how crate design changed between shipments. They should be cross-walked with the surviving 1929 account, customs problem, arrival report and repair feedback.',
      links: rakowLink
    },
    {
      type: '1932 · consular and invoice layer',
      title: 'Consular Certificate for Shipment to Harvard University (1932) and Draft Invoice for Botanical Museum of Harvard University (1932).',
      meta: 'The two documents can separate administrative export identity and declared value from the workshop’s commercial invoice layer. Read beside the 1932 crate sketches, they provide an unusually complete candidate dossier for one late botanical-model shipment.',
      links: rakowLink
    },
    {
      type: '1936 · terminal shipment document',
      title: 'Waybill for Last Shipment to Harvard University (1936).',
      meta: 'The finding aid explicitly identifies the waybill for Rudolf’s final Harvard shipment. It provides a terminal comparison point for the earlier 1907 waybill and makes it possible to ask what changed, and what persisted, in route, carriers, case identity, weight and documentary procedure across nearly three decades.',
      links: rakowLink
    },
    {
      type: '1890s–1906 · value before circulation costs',
      title: 'Invoices (1890–1899) and Notebook: Lists of Models with Prices (1894–1906).',
      meta: 'These records are the workshop-side control needed to distinguish model value from the later costs generated by packing, freight, insurance, customs and brokerage. The distinction is essential wherever a surviving remittance, account figure or shipment total might otherwise be mistaken for the price of the glass itself.',
      links: rakowLink
    }
  ];

  records.forEach((record) => {
    const article = document.createElement('article');
    article.className = 'source-entry';
    article.dataset.sourcePass = '11';
    article.innerHTML = `<p class="source-type">${record.type}</p><h3>${record.title}</h3><p class="source-meta">${record.meta}</p><p class="source-links">${record.links}</p>`;
    list.appendChild(article);
  });

  customsSection.insertAdjacentElement('afterend', section);
})();
